### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by ShikovEgor** [tskoxid/image-filter#1]
1) Какие модели и почему были использованы? (Откуда InceptionV3, на чем файтьюнилась; почему tesseract и т.д.)
2) Адаптация кода для прода (например, ф-л с матами должен читаться только один раз при инициализации)
3) Добавить ноутбук с примерами (где можно), чтобы можно было оценить, как работает код.

**Comment by danwhale** [comment]
палево

https://github.com/tskoxid/image-filter/blob/47cc0fde2df0f0c50544e61f68e5faa30c162052/profane_corpus.csv#L1

**Comment by danwhale** [comment]
![image](https://user-images.githubusercontent.com/23121997/112839248-a27cf080-90a6-11eb-9d06-31ed84678141.png)
эти папки тоже добавить в гитигнор

**Comment by danwhale** [comment]
К адаптации кода для прода, нужно поправить структуру папок под модули, вспомогательные скрипты и тп, а также сделать единую точку иницилизации в корне.  А все данные поместить в соответствующую папку.

**Comment by danwhale** [comment]
Ещё просьба от разрабов: 
```
главное пусть будет одна функция с входной точкой для картинок, которая принимает контент (строкой/байтами/etc) и отдаёт bool
желательно не метод

для текстов отдельная функция, которая возвращает текст со ***
```
